version: '3'
services:
  5wc-site:
    restart: always
    build: . 
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
  redis:
    restart: always
    image: redis:alpine
